AWSTemplateFormatVersion: 2010-09-09
Description: Template to Create IAM Resources
Resources:
  JenkinsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref JenkinsInstanceRole
  JenkinsInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      # RoleName: !Sub '${AWS::StackName}-${AWS::Region}-EC2-Instance-Role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Policies:
        - PolicyName: ssm-secrets-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:GetParametersByPath'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
        - PolicyName: eks-readonly-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'eks:List*'
                  - 'eks:Describe*'
                Resource: '*'
        - PolicyName: ec2-access-for-jenkins
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - 'ec2:DescribeSpotInstanceRequests'
                  - 'ec2:CancelSpotInstanceRequests'
                  - 'ec2:GetConsoleOutput'
                  - 'ec2:RequestSpotInstances'
                  - 'ec2:RunInstances'
                  - 'ec2:StartInstances'
                  - 'ec2:StopInstances'
                  - 'ec2:TerminateInstances'
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeInstanceTypes'
                  - 'ec2:DescribeKeyPairs'
                  - 'ec2:DescribeRegions'
                  - 'ec2:DescribeImages'
                  - 'ec2:DescribeAvailabilityZones'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSubnets'
                  - 'iam:ListInstanceProfilesForRole'
                  - 'iam:PassRole'
                  - 'ec2:GetPasswordData'
  JenkinsAgentProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref JenkinsAgentRole
  JenkinsAgentRole:
    Type: 'AWS::IAM::Role'
    Properties:
      # RoleName: !Sub '${AWS::StackName}-${AWS::Region}-Jenkins-Agent-Role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Policies:
        - PolicyName: ssm-secrets-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:GetParametersByPath'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
  EKSServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKSClusterPolicy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKSVPCResourceController'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/EKSServiceRole'
  EKSNodeInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Sub >-
          arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Path: /
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/EKSNodeInstanceRole'

  KarpenterNodeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'KarpenterNodeRole-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/KarpenterNodeRole'

  KarpenterNodeInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: !Sub 'KarpenterNodeInstanceProfile-${AWS::StackName}'
      Roles:
        - !Ref KarpenterNodeRole  
  PolicyCloudWatchMetrics:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'cloudwatch:PutMetricData'
            Effect: Allow
            Resource: '*'
        Version: 2012-10-17
      PolicyName: !Sub '${AWS::StackName}-${AWS::Region}-PolicyCloudWatchMetrics'
      Roles:
        - !Ref EKSServiceRole
  PolicyELBPermissions:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'ec2:DescribeAccountAttributes'
              - 'ec2:DescribeAddresses'
              - 'ec2:DescribeInternetGateways'
            Effect: Allow
            Resource: '*'
        Version: 2012-10-17
      PolicyName: !Sub '${AWS::StackName}-${AWS::Region}-PolicyELBPermissions'
      Roles:
        - !Ref EKSServiceRole

  PolicyAutoScaling:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'autoscaling:DescribeAutoScalingGroups'
              - 'autoscaling:DescribeAutoScalingInstances'
              - 'autoscaling:DescribeLaunchConfigurations'
              - 'autoscaling:DescribeTags'
              - 'autoscaling:SetDesiredCapacity'
              - 'autoscaling:TerminateInstanceInAutoScalingGroup'
              - 'ec2:DescribeInstanceTypes'
              - 'ec2:DescribeLaunchTemplateVersions'
            Effect: Allow
            Resource: '*'
        Version: 2012-10-17
      PolicyName: !Sub '${AWS::StackName}-${AWS::Region}-PolicyAutoScaling'
      Roles:
        - !Ref EKSNodeInstanceRole

Outputs:
  JenkinsInstanceProfile:
    Description: IAM Instance Profile for Jenkins Instances
    Value: !Sub '${JenkinsInstanceProfile.Arn}'
  JenkinsInstanceRole:
    Description: IAM Role for Jenkins Instances IAM EC2 Profile
    Value: !Sub '${JenkinsInstanceRole.Arn}'
  JenkinsAgentRole:
    Description: IAM Role for Jenkins Instance profile
    Value: !Sub '${JenkinsAgentRole.Arn}'
  JenkinsAgentInstanceProfile:
    Description: IAM instance profile for Jenkins Agent
    Value: !Sub '${JenkinsAgentProfile.Arn}'
  EKSServiceRoleArn:
    Description: EKS service Role
    Value: !Sub '${EKSServiceRole.Arn}'
  EKSNodeInstanceRole:
    Description: IAM Role for EKS Managed Nodes Group
    Value: !Sub '${EKSNodeInstanceRole.Arn}'
  KarpenterNodeRoleArn:
    Description: IAM Role for Karpenter Nodes
    Value: !GetAtt KarpenterNodeRole.Arn
  KarpenterNodeInstanceProfile:
    Description: IAM Instance Profile for Karpenter Nodes
    Value: !GetAtt KarpenterNodeInstanceProfile.Arn
